server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com    #eureka服务端的实例名字 http://eureka7001.com:7001/
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址 查询服务和注册服务都需要依赖这个地址
      #设置与eureka server交互的地址查询服务和注册服务都 3个的话这里用逗号分割
      defaultZone: http://eureka7002.com:7002/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/ 单机

#  server:
#    #默认开启自我保护模式 true 如果90s没收到客户端的心跳，先不剔除，等待90s后再剔除
#    enable-self-preservation: false
#    #更改默认时间 2s
#    eviction-interval-timer-in-ms: 2000